In [38]:
import pandas as pd

In [39]:
info ={
    "name":["lakshay","mannu","ankit","komal"],
    "cgpa":[9.2,9,9.2,8]
}
df=pd.DataFrame(info)

In [40]:
df

      name  cgpa
0  lakshay   9.2
1    mannu   9.0
2    ankit   9.2
3    komal   8.0

In [41]:
s=pd.Series([23,3,4],index=['x','y','z'])
print(s)
print(s.loc['x'])
print(s.iloc[0])

x    23
y     3
z     4
dtype: int64
23
23

In [42]:
#dataframe
info ={
    "name":["lakshay","mannu","ankit","komal"],
    "cgpa":[9.2,9,9.2,8],
    "age":[22,41,18,12]
}
df=pd.DataFrame(info)
df

      name  cgpa  age
0  lakshay   9.2   22
1    mannu   9.0   41
2    ankit   9.2   18
3    komal   8.0   12

In [43]:
#read csv

df=pd.read_csv("employee_data.csv")
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [44]:
df_=pd.read_csv("raw_data.csv")
df_

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [45]:
3 # reading json
df=pd.read_json("employee_data.json")
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [46]:
#methods
df.head()

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [47]:
df.tail(3)

   ID    Name  Age Department  Salary
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [48]:
df=pd.read_csv("globalAirQuality.csv")
df.head()
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [49]:
df.sample()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
7351,2025-11-11 01:25:17.554219,IN,Bengaluru,12.972,77.595,52.232,7.868,3.864,5.333,49.308,0.385,104,21.351,88.427,3.257

In [50]:
# df.loc[0:2,["city","aqi","pm25"]]
# df.iloc[0:2, 2:9]
cities=df["city"].copy()
cities[0]="mumbai"

In [51]:
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [52]:
#filtering of data
# df[(df["aqi"] >100)]
# df[(df["aqi"]>100) & (df["temperature"]>30) &(df["country"] == "US")]
# aqi_data=df[(df["aqi"]>100) & (df["temperature"]>30) &(df["country"] == "US")][["city","aqi"]]
aqi_data=df.loc[(df["aqi"]>100) & (df["temperature"]>30) &(df["country"] == "US"),["city","aqi"]]
aqi_data
aqi_data.loc[6]
aqi_data.iloc[0]

city    New York
aqi          155
Name: 6, dtype: object

In [53]:
df=pd.read_csv("raw_data.csv")

In [54]:
# df.isna().sum()
# df.dropna(axis=1)
# mean=df["age"].mean()
# df["age"].fillna(mean)
cleaned_data=df.copy()
mean=cleaned_data["age"].mean()
cleaned_data["age"]=cleaned_data["age"].fillna(mean)
cleaned_data[["country","income"]]=cleaned_data[["country","income"]].ffill()
cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female  47000.0
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00   India     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [55]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [56]:
df2=df.copy()
df2=df2.fillna(0)
df2["age"]=df2["age"].astype("int64").copy()
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [57]:
#feature engineering
df2=df.copy()
df2["age"]=df2["age"].ffill()
df2["tax"]=df["income"].apply(lambda x : "20%" if x>=60000 else "10%")
df2["Eligibility"]=df["age"].apply(lambda x : "NOT Eligible" if x>=35 else "Eligible")
gender_map={"Male":"M","Female":"F","Unknown":"UN"}
df2["gender"]=df2["gender"].map(gender_map)
df2=df2.assign(new_income=df2["income"]*1.1)
df2["country"]=df2["country"].replace("USA","US")
df2

,id,name,age,country,gender,income,tax,Eligibility,new_income
0,1,John Doe,29.0,US,M,55000.0,10%,Eligible,60500.0
1,1,John Doe,29.0,US,M,55000.0,10%,Eligible,60500.0
2,2,Jane Smith,29.0,Canada,F,62000.0,20%,Eligible,68200.0
3,3,Alex,29.0,US,UN,47000.0,10%,Eligible,51700.0
4,4,Maria Garcia,34.0,Spain,F,NaN,10%,Eligible,NaN
5,5,Li Wei,27.0,China,M,51000.0,10%,Eligible,56100.0
6,6,NaN,45.0,India,F,73000.0,20%,NOT Eligible,80300.0
7,7,Ahmed Khan,38.0,NaN,M,68000.0,20%,NOT Eligible,74800.0
8,8,Rachel Lee,29.0,US,F,62000.0,20%,Eligible,68200.0
9,9,Carlos Ruiz,29.0,Mexico,M,45000.0,10%,Eligible,49500.0
10,10,Emily Davis,31.0,US,NaN,58000.0,10%,Eligible,63800.0

In [58]:
df2.columns=['Id', 'Name', 'Age', 'Country', 'Gender', 'Income', 'Tax',
       'Eligibility', 'New_income']
# i have updated the df here
df2=df2.rename(columns={"Income":"Salary"}) 
# df2.rename(index={1:"first"})
sorted_data=df2.sort_values("Salary").copy()
sorted_data["Ranking"]=sorted_data["Salary"].rank(method="min")
sorted_data
# sorted_data.sort_index()
# sorted_data.reset_index(drop=True)
# reorder cols
sorted_data[['Id', 'Name', 'Age', 'Country', 'Gender', 'Salary','Eligibility', 'New_income','Tax','Ranking']]
sorted_data

,Id,Name,Age,Country,Gender,Salary,Tax,Eligibility,New_income,Ranking
9,9,Carlos Ruiz,29.0,Mexico,M,45000.0,10%,Eligible,49500.0,1.0
3,3,Alex,29.0,US,UN,47000.0,10%,Eligible,51700.0,2.0
5,5,Li Wei,27.0,China,M,51000.0,10%,Eligible,56100.0,3.0
0,1,John Doe,29.0,US,M,55000.0,10%,Eligible,60500.0,4.0
1,1,John Doe,29.0,US,M,55000.0,10%,Eligible,60500.0,4.0
10,10,Emily Davis,31.0,US,NaN,58000.0,10%,Eligible,63800.0,6.0
2,2,Jane Smith,29.0,Canada,F,62000.0,20%,Eligible,68200.0,7.0
8,8,Rachel Lee,29.0,US,F,62000.0,20%,Eligible,68200.0,7.0
7,7,Ahmed Khan,38.0,NaN,M,68000.0,20%,NOT Eligible,74800.0,9.0
6,6,NaN,45.0,India,F,73000.0,20%,NOT Eligible,80300.0,10.0
4,4,Maria Garcia,34.0,Spain,F,NaN,10%,Eligible,NaN,NaN

In [59]:
df2=df2.ffill()
df2

,Id,Name,Age,Country,Gender,Salary,Tax,Eligibility,New_income
0,1,John Doe,29.0,US,M,55000.0,10%,Eligible,60500.0
1,1,John Doe,29.0,US,M,55000.0,10%,Eligible,60500.0
2,2,Jane Smith,29.0,Canada,F,62000.0,20%,Eligible,68200.0
3,3,Alex,29.0,US,UN,47000.0,10%,Eligible,51700.0
4,4,Maria Garcia,34.0,Spain,F,47000.0,10%,Eligible,51700.0
5,5,Li Wei,27.0,China,M,51000.0,10%,Eligible,56100.0
6,6,Li Wei,45.0,India,F,73000.0,20%,NOT Eligible,80300.0
7,7,Ahmed Khan,38.0,India,M,68000.0,20%,NOT Eligible,74800.0
8,8,Rachel Lee,29.0,US,F,62000.0,20%,Eligible,68200.0
9,9,Carlos Ruiz,29.0,Mexico,M,45000.0,10%,Eligible,49500.0
10,10,Emily Davis,31.0,US,M,58000.0,10%,Eligible,63800.0

In [60]:
df2=df.copy()

In [61]:
new_col_order=[col for col in df2.columns if col!="id" ] +["id"]
df2[new_col_order]

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [62]:
df2=df.copy()
df2.drop_duplicates(inplace=True)
df2=df2.ffill()
df2=df2.sort_values("income")
df2=df2.reset_index(drop=True)
df2.to_csv("sorted_data.csv")

In [63]:
df2.groupby("country")["income"].mean()
df2.groupby("country")["income"].max()
df2.groupby("country")["income"].min()

df2.groupby("country")["income"].agg(["mean","max","min"])
df2.groupby("country")["income"].agg(avg_income="mean",max_income="max",min_income="min")

         avg_income  max_income  min_income
country
Canada      62000.0     62000.0     62000.0
China       51000.0     51000.0     51000.0
India       70500.0     73000.0     68000.0
Mexico      45000.0     45000.0     45000.0
Spain       47000.0     47000.0     47000.0
USA         55500.0     62000.0     47000.0

In [64]:
df2.groupby("country").agg({"income":"mean","age":"max"})
df2.groupby("country").agg(avg_income=("income","mean"),avg_age=("age","mean"))

         avg_income  avg_age
country
Canada      62000.0     29.0
China       51000.0     27.0
India       70500.0     41.5
Mexico      45000.0     29.0
Spain       47000.0     34.0
USA         55500.0     29.5

In [65]:
df=pd.DataFrame({"country":["USA","USA","INDIA","INDIA"],
                "year":[2020,2021,2020,2021],
                "sales":[100,120,90,110],
                "profit":[20,25,18,22]})
melted_df=df.melt(
    id_vars=["country","year"],
    value_vars=["sales","profit"],
    var_name="metrics",
    value_name="value"
)
pivoted_df = melted_df.pivot(
    index=["country", "year"],
    columns="metrics",
    values="value"
)

pivoted_df

metrics       profit  sales
country year
INDIA   2020      18     90
        2021      22    110
USA     2020      20    100
        2021      25    120

In [66]:
df

  country  year  sales  profit
0     USA  2020    100      20
1     USA  2021    120      25
2   INDIA  2020     90      18
3   INDIA  2021    110      22

In [67]:
df_customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Adam", "Bob", "Charlie", "Dave"]
})

df_orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [2, 1, 4, 5],
    "amount": [250, 120, 300, 180]
})

In [68]:
df_customers

   customer_id     name
0            1     Adam
1            2      Bob
2            3  Charlie
3            4     Dave

In [69]:
df_orders

   order_id  customer_id  amount
0       101            2     250
1       102            1     120
2       103            4     300
3       104            5     180

In [70]:
pd.merge(
    df_customers,
    df_orders,
    on="customer_id",
    how="inner"
)

   customer_id  name  order_id  amount
0            1  Adam       102     120
1            2   Bob       101     250
2            4  Dave       103     300

In [71]:
pd.merge(
    df_customers,
    df_orders,
    on="customer_id",
    how="left"
)

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0

In [72]:
pd.merge(
    df_customers,
    df_orders,
    on="customer_id",
    how="right"
)

   customer_id  name  order_id  amount
0            2   Bob       101     250
1            1  Adam       102     120
2            4  Dave       103     300
3            5   NaN       104     180

In [73]:
pd.merge(
    df_customers,
    df_orders,
    on="customer_id",
    how="outer"
)

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0
4            5      NaN     104.0   180.0

In [75]:
df.iloc(0)